### ISSUE TITLE
Issues with updated react transition dependency commit

### ISSUE THREAD

**Issue by ecjs** [appleple/react-modal-video#11]
When the `timeout` prop was removed in commit cd406dae8f3389a433cd60c5d39716507a08da81 it created propType errors:

Failed prop type: The prop `timeout` is marked as required in `CSSTransition`, but its value is `undefined`.

I am not super familiar with react-transition-group, but when I looked at the documentation, I only see references to the `timeout` prop, not the newly added `transitionEnterTimeout` and `transitionLeaveTimeout`, I believe these are removed from newer versions.

Am I missing something here?

**Comment by LucienLee** [comment]
It looks like the author mixed up the v1 and v2 API. The `timeout` is required unless provide `addEventListener`. The `transitionEnterTimeout` is only in v1 api.

Refs:
- https://reactcommunity.org/react-transition-group/#Transition-prop-timeout 
- https://github.com/reactjs/react-transition-group/tree/v1-stable

**Comment by marcelautzu** [comment]
getting the same error here, clogging up the console

**Comment by ecjs** [comment]
Do you want a PR to fix this @steelydylan or @plag?

**Comment by steelydylan** [comment]
@ecjs yes Please give us the PR, if you can.
