### ISSUE TITLE
Unclear documentation on using properties

### ISSUE THREAD

**Issue by kwaimind** [appleple/react-modal-video#20]
Hey there, 

Looking over the docs, I'm not 100% sure how I am supposed to use some of the sub-property props.

I.e. "youtube show info" or "youtube controls = 0"

Am I missing something?

**Comment by steelydylan** [comment]
Hi @kwaimind 

eg.
If you want to show youtube video then you can use the sub-property like below

```js
<ModalVideo channel="youtube" youtube={{
  controls: 1
}} />
```
