### ISSUE TITLE
ModalVideo not closing in mobile view.

### ISSUE THREAD

**Issue by harry100** [appleple/react-modal-video#24]
The video plays fine in all the views. It closes when i click the close button or the (overlay) shaded part. But the close option doesn't work in mobile view.
When logging the videoOpen variable that controls the display or closing of the modal, it is set to true when clicking the close option.
Any help on fixing this or am I missing something?

Here's the code
<ModalVideo channel='youtube' isOpen={this.state.videoOpen} videoId={this.props.data.video} onClose={() => this.setState({videoOpen: false})} />

**Comment by abhinavrana** [comment]
I faced same issue, issue is with mobile view landscape mode.
