### ISSUE TITLE
Use function to create ref

### ISSUE THREAD

**Issue by piaaaac** [appleple/react-modal-video#3]
https://github.com/appleple/react-modal-video/blob/21f20f6c4e82e192953ad42518e6b22e1f5fca38/src/index.jsx#L105

lines 105 & 109.

**Comment by steelydylan** [comment]
That means I should change the code from `ref='modal'` to `ref={this.createRef()}` ??
and I want to know the reason

**Comment by alrykov** [comment]
I'm getting an error in console due to legacy syntax
https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs

**Comment by alrykov** [comment]
I could help with moving to new api

**Comment by piaaaac** [comment]
It would be something like this: from `ref='modal'` to `ref={(ref) => {this.refToModal = ref}}`

**Comment by steelydylan** [comment]
@alrykov
Please help me to improve it. If you want to :)
Pull requests are always welcome ;)

**Comment by steelydylan** [comment]
@piaaaac thanks I'll try
