### ISSUE TITLE
Small update to https://appleple.github.io/react-modal-video/ demo code

### ISSUE THREAD

**Issue by victor-cordova** [appleple/react-modal-video#6]
Thanks for this project! Just to avoid confusion, could you please add this piece 
```javascript
onClose={() => this.setState({isOpen: false})} 
```
to the https://appleple.github.io/react-modal-video/ demo code?

**Comment by steelydylan** [comment]
Hi @victor-cordova 
I just added the code to the demo page
Thank you :)
