### ISSUE TITLE
Can't get the modal view to show in Gatsby; I get the window is not defined error.

### ISSUE THREAD

**Issue by Djotchuang** [appleple/react-modal-video#77]
I'm not able to make the modal to show in Gatsby 2.24.64. I get the window is not defined error. I saw that this problem can be solved in Nextjs using the dynamic library, but there isn't a library like that for gatsby. Could someone help me out, please?

I used the code outlined here https://appleple.github.io/react-modal-video/ using react hooks.

**Comment by stevengrimaldo** [comment]
It's also an issue in the latest version of Gatsby as well, 4.6.0.

**Comment by Djotchuang** [comment]
Alright, @stevengrimaldo. Did you find any solutions for the issue?

**Comment by stevengrimaldo** [comment]
@Djotchuang I did! Unfortunately the solution that worked for me that I found after lots of googling was to hard set the version to 1.2.6 in your package.json file.

```
...
"react-modal-video: "1.2.6",
...
```

**Comment by Djotchuang** [comment]
Thanks, @stevengrimaldo I tried that. What I did was delete the line in package.json and package-lock.json and run npm install react-modal-video@1.2.6. I still get the window is undefined error.

Please do you mind sending me the link to the solution you found?

**Comment by Djotchuang** [comment]
The solution is to revert to react-modal-video v1.2.6, which works fine with Gatsby.

**Comment by JonathanLehner** [comment]
works for me too. this is ridiculous... the latest release should work properly
