### ISSUE TITLE
Autoplay documentation

### ISSUE THREAD

**Issue by jbovone** [appleple/react-modal-video#82]
Hi!

I have been working with definitely typed with this package. And, I don't see the actual code that implements the prop autoplay as is used in the Functional Component snippet documentation. 

In every vendor autoplay prop is passed in as a query param contructor inside it's own interface `props.youtube: {autoplay:1}` like so not props.autoplay. 

So I'm not sure about this, because it might happen that I actually miss the line (it happens =D),  but probably worth to check it up. 
Have a nice day!

**Comment by uidev1116** [comment]
@jbovone 

Thanks! 
I am going to fix autoplay documentation.
